SET foreign_key_checks = 0;

TRUNCATE users;
INSERT INTO users (user_id, user_login, user_email, user_admin, user_machine, user_active, user_avatar, user_syncing, user_synced, user_created, user_updated, user_last_login, user_oauth_token, user_oauth_refresh, user_oauth_expiry, user_hash) VALUES (1,'terraform','terraform@example.com',1,0,1,'https://secure.gravatar.com/avatar/aad3747997ae1a5cc149ef80ba32a78b?d=identicon',0,1651434882,1651419573,1651419573,1651435613,_binary 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImlmRkw3ZnNGQ2pQLUxnR1lSX0FDd2xFLXpxVDhGbE5Lc085S3NlcFBsRnMiLCJ0eXAiOiJKV1QifQ.eyJnbnQiOjEsInR0IjowLCJleHAiOjE2NTE0MzkyMTMsImlhdCI6MTY1MTQzNTYxM30.bzm2vjjsE-vTqPQyOq2V_Eh_Cab23rtzeVHgxaWEIdO-skmLbEig_rFilo3g-tUsLStHyqCjM2lx6TXXH2WkrmeZVwtdO6aP2Bo4Op0qEeCvEOBVCYOIcVd-UCXzicSLi5oiX2SvbdZH_p9tMDiWFtQxuPClhqENoznGYoRVBMMPgD64hMj4J6706wserjyQdD6PuyoQAahdOnCzNkplhSmBDSMgUCeqgVMp55OqMKcjKjRu8MfpwmM2T01WvKrEBb7E5NpWc2nxVM109yh_e71Benac-ixGahkdpM-ho3IMuWuQxkO-19KYAJIBf0j-Sw311O1JCurFgWmYvCSYWcfE-AvMNokqKhC4KhElSNybo9hR-M4EyWuOxuiWGtUcx-x7BciTYGEDOp57m9GcLeOb7YKRmXYZusWF7p0k5eBunuJ9J2kfOEpz7_TxoxeRtrRFUowOOPDvzOPKiKKYRsL4G2IjEw4R_468HljWfGLjqEn9d2gfBGOjMgKY-85_z7p4DDlbO2GIoQlaNP_tp7_Ym6Kjp16nuwPLGfhnV59rUbA8UNspY5fbqHu28Au3pF8uth0J88VJhLfwSLwqfsKR3L0OgMvCmKhH1pIJ2lqMp4ng4--tWZnYx8DXq8Borxk4Jz8y5yq_pXEafBrI36GOZ_D5xuXFRiE83m79PE0',_binary 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImlmRkw3ZnNGQ2pQLUxnR1lSX0FDd2xFLXpxVDhGbE5Lc085S3NlcFBsRnMiLCJ0eXAiOiJKV1QifQ.eyJnbnQiOjEsInR0IjoxLCJleHAiOjE5MTQyMzU2MTMsImlhdCI6MTY1MTQzNTYxM30.GgNXUrPpKYCUcThjArMyNjYo8wZt_JT_zT79gqNcJPXSMy7KNB5dR8o_dfCZWWcwC5pWAhjHB8JCfrLcKmMfYDxaj1S1cooNypjh_mGd-BHmz5IbBPBaFV-xYj3mArKZ_d2avZBK0NxxWsdwTuOfXdmnCz68Z7C9K6NCN6hGm5ilb2XOAUtyVtCrgURLP6GB1cM7CAyFOiMWF3MAiXZcGkXP-lZ5v1_CEB8I8X8AinsdRsNhRXruJfAvFnNscHZmGIh0r4jJG-_Qe9tZGbnZsuFDQpNaGu4tlD1bOfEM4roEsUXPkceAE9fv9HWr1yhHi4amEgACR79RPccRC3huZUoO0wRGswAJEGdBLLDu6WlqTD9YevLEqveIBJf5zbQyycuVfHBjuSSNaJjowC40qlbkbi8aQZWOB94X45z7jhoaPernU6oMz9-CaoU1yP-qfhR-rJc5q2ItTHbjb8KZ2_D2hyLyNFyLj38fWnUrVVHxcZfgs1jUjg5o4_e5TiM9mQPl1ef3Y-QAr02_viJe7qOvrP2oRqDByJQSczkJsRK9OGK4d-heVh1za-3PsQAwAoAKizKfsIu8saMExG4WFz32VnBcp3dtRKmtNYc_iDyZg1-VJKEBHS3iuX6FNMFcH10oZceIEcG7X07j6owkCel27ptvZVe344S1-HfUFD8',1651439213,'5PVYqFHjdYWpzyOk6PVj9OUQULibBJeL');

TRUNCATE repos;
INSERT INTO repos (repo_id, repo_uid, repo_user_id, repo_namespace, repo_name, repo_slug, repo_scm, repo_clone_url, repo_ssh_url, repo_html_url, repo_active, repo_private, repo_visibility, repo_branch, repo_counter, repo_config, repo_timeout, repo_trusted, repo_protected, repo_synced, repo_created, repo_updated, repo_version, repo_signer, repo_secret, repo_no_forks, repo_no_pulls, repo_cancel_pulls, repo_cancel_push, repo_throttle, repo_cancel_running) VALUES (1,'1',1,'terraform','demo1','terraform/demo1','','http://localhost:3000/terraform/demo1.git','ssh://git@localhost:2222/terraform/demo1.git','http://localhost:3000/terraform/demo1',1,0,'public','master',0,'.drone.yml',60,0,0,1651419677,1651419677,1651419677,3,'ehmqpbTbzZTJ5VJqc05JDrCKcIhGY2GJ','MBoK8zF8H5cyHC2RRX1WoCWwVEJXp5mr',1,1,0,0,0,0);
INSERT INTO repos (repo_id, repo_uid, repo_user_id, repo_namespace, repo_name, repo_slug, repo_scm, repo_clone_url, repo_ssh_url, repo_html_url, repo_active, repo_private, repo_visibility, repo_branch, repo_counter, repo_config, repo_timeout, repo_trusted, repo_protected, repo_synced, repo_created, repo_updated, repo_version, repo_signer, repo_secret, repo_no_forks, repo_no_pulls, repo_cancel_pulls, repo_cancel_push, repo_throttle, repo_cancel_running) VALUES (2,'2',0,'terraform','demo2','terraform/demo2','','http://localhost:3000/terraform/demo2.git','ssh://git@localhost:2222/terraform/demo2.git','http://localhost:3000/terraform/demo2',0,0,'public','master',0,'',0,0,0,1651419677,1651419677,1651419677,1,'','',0,0,0,0,0,0);
INSERT INTO repos (repo_id, repo_uid, repo_user_id, repo_namespace, repo_name, repo_slug, repo_scm, repo_clone_url, repo_ssh_url, repo_html_url, repo_active, repo_private, repo_visibility, repo_branch, repo_counter, repo_config, repo_timeout, repo_trusted, repo_protected, repo_synced, repo_created, repo_updated, repo_version, repo_signer, repo_secret, repo_no_forks, repo_no_pulls, repo_cancel_pulls, repo_cancel_push, repo_throttle, repo_cancel_running) VALUES (3,'3',0,'terraform','demo3','terraform/demo3','','http://localhost:3000/terraform/demo3.git','ssh://git@localhost:2222/terraform/demo3.git','http://localhost:3000/terraform/demo3',0,0,'public','master',0,'',0,0,0,1651419677,1651419677,1651419677,1,'','',0,0,0,0,0,0);

TRUNCATE secrets;
INSERT INTO secrets (secret_id, secret_repo_id, secret_name, secret_data, secret_pull_request, secret_pull_request_push) VALUES (1,1,'TEST_SECRET',_binary 'secret',1,0);

TRUNCATE cron;
INSERT INTO cron (cron_id, cron_repo_id, cron_name, cron_expr, cron_next, cron_prev, cron_event, cron_branch, cron_target, cron_disabled, cron_created, cron_updated, cron_version) VALUES (1,1,'test-cron','@hourly',1651420800,0,'push','master','',0,0,0,0);

TRUNCATE orgsecrets;
INSERT INTO orgsecrets (secret_id, secret_namespace, secret_name, secret_type, secret_data, secret_pull_request, secret_pull_request_push) VALUES (1,'terraform','TEST_ORG_SECRET','',_binary 'org-secret',1,0);

TRUNCATE templates;
INSERT INTO templates (template_id, template_name, template_namespace, template_data, template_created, template_updated) VALUES (1,'test-template.jsonnet','terraform',_binary '/* A Jsonnet template example. */\nlocal stepName = std.extVar(\"input.stepName\");\nlocal image = std.extVar(\"input.image\");\nlocal commands = std.extVar(\"input.commands\");\n{\n  \"kind\": \"pipeline\",\n  \"type\": \"docker\",\n  \"name\": \"default\",\n  \"steps\": [\n    {\n      \"name\": stepName,\n      \"image\": image,\n      \"commands\": [\n        commands\n      ]\n    }\n  ]\n}\n',0,0);

SET foreign_key_checks = 1;